### PR TITLE
update recast to v0.11.12

### PR DESCRIPTION
**Pull request by hzoo**

### CODE REVIEW

**Comment by eventualbuddha** [comment]
This project is deprecated, FYI.

**Comment by hzoo** [comment]
Sorry, no context - https://twitter.com/zpao/status/771502203559223297

Yeah, I figured it was but it's being used in html-loader right now cc @hemanth

**Comment by eventualbuddha** [comment]
Okay, well I released v0.2.3 with this change.

**Comment by hemanth** [comment]
Thank you!

**Pull request merged**
